baseURL = "http://antoniopagano.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
pagination.pagerSize = 6
enableRobotsTXT = true
title = "Antonio Pagano"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 10
